- name: install vim-enhanced package
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install vim-enhanced package
      yum:
        name: vim-enhanced
        state: present
